# Generated by Django 4.2.7 on 2025-11-28 09:41

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('channel_partners', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(db_index=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('age', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(100)])),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('locality', models.CharField(blank=True, max_length=200)),
                ('current_residence', models.CharField(blank=True, choices=[('own', 'Own'), ('rent', 'Rent')], max_length=10)),
                ('occupation', models.CharField(blank=True, choices=[('self_emp', 'Self Employed'), ('service', 'Service'), ('homemaker', 'Homemaker'), ('business', 'Business'), ('retired', 'Retired'), ('other', 'Other')], max_length=20)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('designation', models.CharField(blank=True, max_length=200)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('purpose', models.CharField(blank=True, choices=[('investment', 'Investment'), ('first_home', 'First Home'), ('second_home', 'Second Home'), ('retirement_home', 'Retirement Home')], max_length=20)),
                ('visit_type', models.CharField(blank=True, choices=[('family', 'Family'), ('alone', 'Alone')], max_length=10)),
                ('is_first_visit', models.BooleanField(default=True)),
                ('how_did_you_hear', models.CharField(blank=True, max_length=200)),
                ('cp_firm_name', models.CharField(blank=True, max_length=200)),
                ('cp_name', models.CharField(blank=True, max_length=200)),
                ('cp_phone', models.CharField(blank=True, max_length=15)),
                ('cp_rera_number', models.CharField(blank=True, max_length=50)),
                ('is_pretagged', models.BooleanField(default=False)),
                ('pretag_status', models.CharField(blank=True, choices=[('pending_verification', 'Pending Verification'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending_verification', max_length=20)),
                ('phone_verified', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('visit_scheduled', 'Visit Scheduled'), ('visit_completed', 'Visit Completed'), ('discussion', 'Discussion'), ('hot', 'Hot'), ('ready_to_book', 'Ready to Book'), ('booked', 'Booked'), ('lost', 'Lost')], db_index=True, default='new', max_length=20)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('assigned_by', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['super_admin', 'mandate_owner', 'site_head']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_assignments', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['closing_manager', 'telecaller', 'sourcing_manager']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL)),
                ('channel_partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='channel_partners.channelpartner')),
                ('configuration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='projects.projectconfiguration')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_leads', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='projects.project')),
            ],
            options={
                'db_table': 'leads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OtpLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_hash', models.CharField(max_length=64)),
                ('otp_code', models.CharField(max_length=6)),
                ('attempts', models.IntegerField(default=0)),
                ('max_attempts', models.IntegerField(default=3)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_logs', to='leads.lead')),
                ('sent_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'otp_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FollowUpReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_date', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='leads.lead')),
            ],
            options={
                'db_table': 'follow_up_reminders',
                'ordering': ['reminder_date'],
            },
        ),
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(choices=[('connected', 'Connected'), ('not_reachable', 'Not Reachable'), ('switched_off', 'Switched Off'), ('wrong_number', 'Wrong Number'), ('busy', 'Busy')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('call_duration', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('called_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_logs', to='leads.lead')),
            ],
            options={
                'db_table': 'call_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['phone', 'status'], name='leads_phone_14b340_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['project', 'status'], name='leads_project_2ea127_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['is_pretagged', 'pretag_status'], name='leads_is_pret_f8bb18_idx'),
        ),
    ]
