# Generated by Django 4.2.7 on 2025-11-28 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='followupreminder',
            name='reminder_type',
            field=models.CharField(choices=[('callback', 'Callback'), ('payment_followup', 'Payment Follow-up'), ('visit_reminder', 'Visit Reminder')], default='callback', max_length=20),
        ),
    ]
