# Generated by Django 4.2.7 on 2025-11-28 19:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0002_project_commercial_floors_and_more'),
        ('leads', '0002_followupreminder_reminder_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAssignmentQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_quota', models.IntegerField(default=0, help_text='Number of leads to assign daily')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(limit_choices_to={'role__in': ['super_admin', 'site_head']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_quotas', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(limit_choices_to={'role__in': ['closing_manager', 'telecaller', 'sourcing_manager']}, on_delete=django.db.models.deletion.CASCADE, related_name='daily_quotas', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_quotas', to='projects.project')),
            ],
            options={
                'db_table': 'daily_assignment_quotas',
                'ordering': ['-created_at'],
                'unique_together': {('project', 'employee')},
            },
        ),
    ]
