# Generated by Django 4.2.7 on 2025-11-29 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_dailyassignmentquota'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='notes',
            field=models.TextField(blank=True, help_text='General notes about the lead, conversations, preferences, etc.'),
        ),
    ]
