# Generated by Django 4.2.7 on 2025-11-29 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_lead_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='visit_source',
            field=models.CharField(blank=True, choices=[('call', 'Call Generated'), ('cp', 'Channel Partner'), ('walkin', 'Direct Walk-in')], help_text='How was this visit generated? (Call, CP, or Walk-in)', max_length=20, null=True),
        ),
    ]
