# Generated by Django 4.2.7 on 2025-11-29 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_lead_visit_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otplog',
            name='otp_code',
        ),
        migrations.AddField(
            model_name='otplog',
            name='gateway_response',
            field=models.TextField(blank=True, help_text='SMS gateway response (JSON)'),
        ),
        migrations.AlterField(
            model_name='otplog',
            name='otp_hash',
            field=models.CharField(max_length=128),
        ),
    ]
