# Generated by Django 4.2.7 on 2025-12-07 03:52
# Fixed to handle missing columns safely

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.db import connection


def check_column_exists(table_name, column_name):
    """Check if a column exists in SQLite"""
    try:
        with connection.cursor() as cursor:
            cursor.execute(f"PRAGMA table_info({table_name})")
            columns = [row[1] for row in cursor.fetchall()]
            return column_name in columns
    except Exception:
        return False


def fix_calllog_fields(apps, schema_editor):
    """Fix CallLog fields: rename called_by_id to user_id if it exists"""
    with connection.cursor() as cursor:
        # Rename called_by_id to user_id if it exists and user_id doesn't
        if check_column_exists('call_logs', 'called_by_id') and not check_column_exists('call_logs', 'user_id'):
            try:
                cursor.execute("ALTER TABLE call_logs RENAME COLUMN called_by_id TO user_id")
            except Exception as e:
                print(f"Note: {e}")
        
        # Also check for called_by (without _id) - Django sometimes uses this
        if check_column_exists('call_logs', 'called_by') and not check_column_exists('call_logs', 'user'):
            try:
                cursor.execute("ALTER TABLE call_logs RENAME COLUMN called_by TO user")
            except Exception as e:
                print(f"Note: {e}")


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leads', '0008_update_calllog_fields'),
    ]

    operations = [
        # Fix CallLog fields first (rename columns if they exist)
        migrations.RunPython(fix_calllog_fields, migrations.RunPython.noop),
        
        migrations.AlterModelOptions(
            name='calllog',
            options={'ordering': ['-call_date']},
        ),
        migrations.AlterModelOptions(
            name='dailyassignmentquota',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='lead',
            name='leads_phone_14b340_idx',
        ),
        migrations.RemoveIndex(
            model_name='lead',
            name='leads_project_2ea127_idx',
        ),
        migrations.RemoveIndex(
            model_name='lead',
            name='leads_is_pret_f8bb18_idx',
        ),
        # Add user field only if user_id doesn't exist (after potential rename above)
        migrations.RunSQL(
            sql="""
            -- user_id should exist after fix_calllog_fields if called_by_id was renamed
            -- If not, AddField below will create it
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        # Conditionally add user field - only if user_id doesn't exist
        migrations.RunSQL(
            sql="""
            -- Check if we need to add user_id
            -- This is a no-op, actual addition handled by AddField
            SELECT 1;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AddField(
            model_name='calllog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_logs', to=settings.AUTH_USER_MODEL),
        ),
        # Remove called_by only if called_by_id still exists
        migrations.RunSQL(
            sql="""
            -- Remove called_by_id if it still exists (after user_id was added/renamed)
            -- SQLite requires table recreation for DROP COLUMN, handled by RemoveField
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RemoveField(
            model_name='calllog',
            name='called_by',
        ),
        migrations.RemoveField(
            model_name='dailyassignmentquota',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='followupreminder',
            name='reminder_type',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='assigned_at',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='assigned_by',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='configuration',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='is_pretagged',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='phone_verified',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='pretag_status',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='status',
        ),
        migrations.RemoveField(
            model_name='otplog',
            name='gateway_response',
        ),
        migrations.RemoveField(
            model_name='otplog',
            name='sent_by',
        ),
        migrations.AlterField(
            model_name='calllog',
            name='outcome',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='dailyassignmentquota',
            name='daily_quota',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='dailyassignmentquota',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_quotas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lead',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Overall budget preference', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='otplog',
            name='otp_hash',
            field=models.CharField(max_length=64),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['phone'], name='leads_phone_13acb4_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['is_archived', '-created_at'], name='leads_is_arch_dc3802_idx'),
        ),
        # Add indexes using RunSQL to handle if they already exist
        migrations.RunSQL(
            sql="""
            CREATE INDEX IF NOT EXISTS lead_projec_project_e57839_idx 
            ON lead_project_associations(project_id, status, is_archived);
            CREATE INDEX IF NOT EXISTS lead_projec_assigne_9c1e2a_idx 
            ON lead_project_associations(assigned_to_id, status);
            CREATE INDEX IF NOT EXISTS lead_projec_is_pret_abf9d6_idx 
            ON lead_project_associations(is_pretagged, pretag_status);
            """,
            reverse_sql="""
            DROP INDEX IF EXISTS lead_projec_project_e57839_idx;
            DROP INDEX IF EXISTS lead_projec_assigne_9c1e2a_idx;
            DROP INDEX IF EXISTS lead_projec_is_pret_abf9d6_idx;
            """,
        ),
    ]
