# Generated by Django 4.2.7 on 2025-12-07 04:19
# Fixed: Only add indexes, don't rename call_duration (it's already duration_minutes)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_alter_calllog_options_and_more'),
    ]

    operations = [
        # Only add indexes - call_duration was already renamed to duration_minutes
        # by migration 0008 or manually by fix_all_migrations.py
        migrations.RunSQL(
            sql="""
            CREATE INDEX IF NOT EXISTS lead_projec_project_e57839_idx 
            ON lead_project_associations(project_id, status, is_archived);
            CREATE INDEX IF NOT EXISTS lead_projec_assigne_9c1e2a_idx 
            ON lead_project_associations(assigned_to_id, status);
            CREATE INDEX IF NOT EXISTS lead_projec_is_pret_abf9d6_idx 
            ON lead_project_associations(is_pretagged, pretag_status);
            """,
            reverse_sql="""
            DROP INDEX IF EXISTS lead_projec_project_e57839_idx;
            DROP INDEX IF EXISTS lead_projec_assigne_9c1e2a_idx;
            DROP INDEX IF EXISTS lead_projec_is_pret_abf9d6_idx;
            """,
        ),
    ]
