# Generated by Django 4.2.7 on 2025-12-07
# Fixed: Use RunSQL with IF NOT EXISTS to safely create indexes

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0012_add_missing_indexes'),
    ]

    operations = [
        # Use RunSQL with IF NOT EXISTS to safely create indexes
        # Migration 0012 already created these, but Django's state thinks they don't exist
        migrations.RunSQL(
            sql="""
            CREATE INDEX IF NOT EXISTS lead_projec_project_e57839_idx 
            ON lead_project_associations(project_id, status, is_archived);
            CREATE INDEX IF NOT EXISTS lead_projec_assigne_9c1e2a_idx 
            ON lead_project_associations(assigned_to_id, status);
            CREATE INDEX IF NOT EXISTS lead_projec_is_pret_abf9d6_idx 
            ON lead_project_associations(is_pretagged, pretag_status);
            """,
            reverse_sql="""
            DROP INDEX IF EXISTS lead_projec_project_e57839_idx;
            DROP INDEX IF EXISTS lead_projec_assigne_9c1e2a_idx;
            DROP INDEX IF EXISTS lead_projec_is_pret_abf9d6_idx;
            """,
        ),
    ]
