# Generated by Django 4.2.7 on 2025-12-07 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0015_leadprojectassociation_lead_projec_project_e57839_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='otplog',
            name='gateway_response',
            field=models.TextField(blank=True, help_text='SMS gateway response (JSON)'),
        ),
        migrations.AlterField(
            model_name='otplog',
            name='otp_hash',
            field=models.CharField(max_length=128),
        ),
        # Indexes already exist from migration 0015, so skip them here
    ]
