# Generated by Django 4.2.7 on 2025-12-11 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0016_otplog_gateway_response_alter_otplog_otp_hash_and_more'),
    ]

    operations = [
        # Indexes already exist from previous migrations, so skip them here
    ]
