# Generated by Django 4.2.7 on 2025-12-11 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0017_leadprojectassociation_lead_projec_project_e57839_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='is_pretagged',
            field=models.BooleanField(default=False, help_text='DEPRECATED: Use LeadProjectAssociation.is_pretagged instead'),
        ),
    ]
