# Generated by Django 4.2.7 on 2025-12-13 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0019_leadprojectassociation_lead_projec_project_e57839_idx_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="CREATE INDEX IF NOT EXISTS lead_projec_project_e57839_idx ON lead_project_associations(project_id, status, is_archived);",
            reverse_sql="DROP INDEX IF EXISTS lead_projec_project_e57839_idx;",
        ),
        migrations.RunSQL(
            sql="CREATE INDEX IF NOT EXISTS lead_projec_assigne_9c1e2a_idx ON lead_project_associations(assigned_to_id, status);",
            reverse_sql="DROP INDEX IF EXISTS lead_projec_assigne_9c1e2a_idx;",
        ),
        migrations.RunSQL(
            sql="CREATE INDEX IF NOT EXISTS lead_projec_is_pret_abf9d6_idx ON lead_project_associations(is_pretagged, pretag_status);",
            reverse_sql="DROP INDEX IF EXISTS lead_projec_is_pret_abf9d6_idx;",
        ),
    ]
