# Generated by Django 4.2.7 on 2025-12-17 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0020_leadprojectassociation_lead_projec_project_e57839_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadprojectassociation',
            name='time_frame',
            field=models.CharField(blank=True, choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening')], help_text='Preferred time frame for visit', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='leadprojectassociation',
            name='visit_scheduled_date',
            field=models.DateTimeField(blank=True, help_text='Scheduled date and time for visit', null=True),
        ),
        # Note: Indexes are already created in migration 0020, so we don't need to add them again
    ]
