# Generated by Django 4.2.7 on 2025-12-17 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0021_add_time_frame_fields'),
    ]

    operations = [
        # Use RunSQL to safely create indexes that may already exist
        # This ensures the migration state is correct without failing if indexes exist
        migrations.RunSQL(
            sql="""
            CREATE INDEX IF NOT EXISTS lead_projec_project_e57839_idx 
            ON lead_project_associations(project_id, status, is_archived);
            CREATE INDEX IF NOT EXISTS lead_projec_assigne_9c1e2a_idx 
            ON lead_project_associations(assigned_to_id, status);
            CREATE INDEX IF NOT EXISTS lead_projec_is_pret_abf9d6_idx 
            ON lead_project_associations(is_pretagged, pretag_status);
            """,
            reverse_sql="""
            DROP INDEX IF EXISTS lead_projec_project_e57839_idx;
            DROP INDEX IF EXISTS lead_projec_assigne_9c1e2a_idx;
            DROP INDEX IF EXISTS lead_projec_is_pret_abf9d6_idx;
            """,
        ),
    ]
