# Generated by Django 4.2.7 on 2025-12-18 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0022_leadprojectassociation_lead_projec_project_e57839_idx_and_more'),
    ]

    operations = [
        # Indexes were already created in migration 0022 using RunSQL with IF NOT EXISTS
        # No need to recreate them here
    ]
