# Generated by Django 4.2.7 on 2025-12-18 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0023_change_booking_to_foreignkey'),
    ]

    operations = [
        # Indexes were already created in migration 0022 using RunSQL with IF NOT EXISTS
        # No need to recreate them here
    ]
