# Generated by Django 4.2.7 on 2026-01-01 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0024_leadprojectassociation_lead_projec_project_e57839_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='leadprojectassociation',
            index=models.Index(fields=['project', 'status', 'is_archived'], name='lead_projec_project_e57839_idx'),
        ),
        migrations.AddIndex(
            model_name='leadprojectassociation',
            index=models.Index(fields=['assigned_to', 'status'], name='lead_projec_assigne_9c1e2a_idx'),
        ),
        migrations.AddIndex(
            model_name='leadprojectassociation',
            index=models.Index(fields=['is_pretagged', 'pretag_status'], name='lead_projec_is_pret_abf9d6_idx'),
        ),
    ]
