# Generated by Django 4.2.7 on 2026-01-01 21:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leads', '0025_leadprojectassociation_lead_projec_project_e57839_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadprojectassociation',
            name='is_revisit',
            field=models.BooleanField(default=False, help_text='Is this a revisit?'),
        ),
        migrations.AddField(
            model_name='leadprojectassociation',
            name='previous_visit',
            field=models.ForeignKey(blank=True, help_text='Link to previous visit association', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisits', to='leads.leadprojectassociation'),
        ),
        migrations.AddField(
            model_name='leadprojectassociation',
            name='queued_at',
            field=models.DateTimeField(blank=True, help_text='When the visit was queued', null=True),
        ),
        migrations.AddField(
            model_name='leadprojectassociation',
            name='queued_by',
            field=models.ForeignKey(blank=True, help_text='Telecaller who queued the visit', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queued_visits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leadprojectassociation',
            name='revisit_count',
            field=models.IntegerField(default=0, help_text='Number of times client revisited'),
        ),
        migrations.AddField(
            model_name='leadprojectassociation',
            name='revisit_reason',
            field=models.TextField(blank=True, help_text='Reason for revisit'),
        ),
        migrations.AlterField(
            model_name='leadprojectassociation',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('visit_scheduled', 'Visit Scheduled'), ('queued_visit', 'Queued Visit'), ('visit_completed', 'Visit Completed'), ('discussion', 'Discussion'), ('hot', 'Hot'), ('ready_to_book', 'Ready to Book'), ('booked', 'Booked'), ('lost', 'Lost')], db_index=True, default='new', max_length=20),
        ),
    ]
