# Generated by Django 4.2.7 on 2026-01-12 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0026_leadprojectassociation_is_revisit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadprojectassociation',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('visit_scheduled', 'Visit Scheduled'), ('queued_visit', 'Queued Visit'), ('visit_completed', 'Visit Completed'), ('discussion', 'Discussion'), ('hot', 'Hot'), ('ready_to_book', 'Ready to Book'), ('booked', 'Booked'), ('lost', 'Lost'), ('not_interested', 'Not Interested')], db_index=True, default='new', max_length=20),
        ),
    ]
