# Generated by Django 4.2.7 on 2025-11-28 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('builder_name', models.CharField(max_length=200)),
                ('location', models.TextField()),
                ('rera_id', models.CharField(blank=True, max_length=50)),
                ('project_type', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('mixed', 'Mixed')], default='residential', max_length=20)),
                ('starting_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('inventory_summary', models.TextField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('default_commission_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('auto_assignment_strategy', models.CharField(choices=[('round_robin', 'Round Robin'), ('manual', 'Manual')], default='manual', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mandate_owner', models.ForeignKey(limit_choices_to={'role': 'mandate_owner'}, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
                ('site_head', models.ForeignKey(blank=True, limit_choices_to={'role': 'site_head'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to='projects.project')),
            ],
            options={
                'db_table': 'project_configurations',
                'unique_together': {('project', 'name')},
            },
        ),
        migrations.CreateModel(
            name='PaymentMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_milestones', to='projects.project')),
            ],
            options={
                'db_table': 'payment_milestones',
                'ordering': ['order'],
                'unique_together': {('project', 'name')},
            },
        ),
    ]
