# Generated by Django 4.2.7 on 2025-11-28 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='commercial_floors',
            field=models.IntegerField(default=0, help_text='Number of floors with commercial units'),
        ),
        migrations.AddField(
            model_name='project',
            name='commercial_units_per_floor',
            field=models.IntegerField(default=0, help_text='Number of commercial units per floor'),
        ),
        migrations.AddField(
            model_name='project',
            name='floors_per_tower',
            field=models.IntegerField(default=1, help_text='Number of floors in each tower'),
        ),
        migrations.AddField(
            model_name='project',
            name='has_commercial',
            field=models.BooleanField(default=False, help_text='Does this project have commercial units?'),
        ),
        migrations.AddField(
            model_name='project',
            name='number_of_towers',
            field=models.IntegerField(default=1, help_text='Total number of towers'),
        ),
        migrations.AddField(
            model_name='project',
            name='units_per_floor',
            field=models.IntegerField(default=1, help_text='Number of residential units per floor'),
        ),
    ]
