# Generated by Django 4.2.7 on 2025-11-29 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_commercial_floors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, help_text='Cover image for project cards and detail page', null=True, upload_to='projects/'),
        ),
    ]
