# Generated by Django 4.2.7 on 2025-11-30 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ending_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='ending_price_unit',
            field=models.CharField(blank=True, choices=[('lakhs', 'Lakhs'), ('crores', 'Crores')], default='lakhs', max_length=10),
        ),
        migrations.AddField(
            model_name='project',
            name='starting_price_unit',
            field=models.CharField(blank=True, choices=[('lakhs', 'Lakhs'), ('crores', 'Crores')], default='lakhs', max_length=10),
        ),
    ]
