# Generated by Django 4.2.7 on 2025-12-02 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_ending_price_project_ending_price_unit_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectconfiguration',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='projectconfiguration',
            name='development_charges_percent',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Development charges percentage', max_digits=5),
        ),
        migrations.AddField(
            model_name='projectconfiguration',
            name='gst_percent',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='GST percentage (default 5%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='projectconfiguration',
            name='legal_charges',
            field=models.DecimalField(decimal_places=2, default=30000.0, help_text='Legal charges (default ₹30,000)', max_digits=10),
        ),
        migrations.AddField(
            model_name='projectconfiguration',
            name='price_per_sqft',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price per square foot', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='projectconfiguration',
            name='registration_charges',
            field=models.DecimalField(decimal_places=2, default=30000.0, help_text='Registration charges (default ₹30,000)', max_digits=10),
        ),
        migrations.AddField(
            model_name='projectconfiguration',
            name='stamp_duty_percent',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='Stamp duty percentage (default 5%)', max_digits=5),
        ),
        migrations.CreateModel(
            name='ConfigurationFloorMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_number', models.IntegerField(help_text='Floor number (1 = Ground floor, 2 = First floor, etc.)')),
                ('units_per_floor', models.IntegerField(default=1, help_text='Number of units of this configuration on this floor')),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floor_mappings', to='projects.projectconfiguration')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floor_configurations', to='projects.project')),
            ],
            options={
                'db_table': 'configuration_floor_mappings',
                'ordering': ['floor_number', 'configuration__name'],
                'unique_together': {('project', 'configuration', 'floor_number')},
            },
        ),
        migrations.CreateModel(
            name='ConfigurationAreaType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carpet_area', models.DecimalField(decimal_places=2, help_text='Carpet area in sqft', max_digits=10)),
                ('buildup_area', models.DecimalField(decimal_places=2, help_text='Buildup area in sqft', max_digits=10)),
                ('rera_area', models.DecimalField(blank=True, decimal_places=2, help_text='RERA area in sqft', max_digits=10, null=True)),
                ('description', models.CharField(blank=True, help_text="Optional description (e.g., 'Compact', 'Spacious')", max_length=200)),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area_types', to='projects.projectconfiguration')),
            ],
            options={
                'db_table': 'configuration_area_types',
                'ordering': ['carpet_area'],
                'unique_together': {('configuration', 'carpet_area', 'buildup_area')},
            },
        ),
    ]
