# Generated by Django 4.2.7 on 2025-12-02 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_projectconfiguration_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectconfiguration',
            name='development_charges_percent',
        ),
        migrations.AddField(
            model_name='configurationfloormapping',
            name='unit_number_start',
            field=models.IntegerField(default=1, help_text='Starting unit number for this floor (e.g., 201 for floor 2, unit 1)'),
        ),
        migrations.AddField(
            model_name='projectconfiguration',
            name='development_charges',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Development charges (flat amount in ₹)', max_digits=10),
        ),
    ]
