# Generated by Django 4.2.7 on 2025-12-02 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_change_development_charges_and_add_unit_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_number', models.IntegerField(help_text='Floor number (1 = Ground floor, 2 = First floor, etc.)')),
                ('unit_number', models.IntegerField(help_text='Unit number (e.g., 101, 102, 201, 202)')),
                ('is_excluded', models.BooleanField(default=False, help_text='Exclude this unit (e.g., for commercial floors)')),
                ('area_type', models.ForeignKey(blank=True, help_text='Configuration variant assigned to this unit (e.g., 1BHK-379sqft)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit_configurations', to='projects.configurationareatype')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_configurations', to='projects.project')),
            ],
            options={
                'db_table': 'unit_configurations',
                'ordering': ['floor_number', 'unit_number'],
                'unique_together': {('project', 'floor_number', 'unit_number')},
            },
        ),
    ]
