# Generated by Django 4.2.7 on 2025-12-02 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_add_unit_configuration_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unitconfiguration',
            options={'ordering': ['tower_number', 'floor_number', 'unit_number']},
        ),
        migrations.AlterUniqueTogether(
            name='unitconfiguration',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='unitconfiguration',
            name='tower_number',
            field=models.IntegerField(default=1, help_text='Tower number (1, 2, 3, etc.)'),
        ),
        migrations.AlterField(
            model_name='unitconfiguration',
            name='unit_number',
            field=models.IntegerField(help_text='Unit number (e.g., 101, 102, 201, 202) - same numbers can exist in different towers'),
        ),
        migrations.AlterUniqueTogether(
            name='unitconfiguration',
            unique_together={('project', 'tower_number', 'floor_number', 'unit_number')},
        ),
    ]
