# Generated by Django 4.2.7 on 2025-12-11 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_add_tower_number_to_unit_configuration'),
    ]

    operations = [
        migrations.CreateModel(
            name='TowerFloorConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tower_number', models.IntegerField(help_text='Tower number (1, 2, 3, etc.)')),
                ('floors_count', models.IntegerField(default=1, help_text='Number of floors in this tower')),
                ('units_per_floor', models.IntegerField(default=1, help_text='Number of units per floor in this tower')),
                ('is_commercial', models.BooleanField(default=False, help_text='Is this tower commercial?')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tower_floor_configs', to='projects.project')),
            ],
            options={
                'db_table': 'tower_floor_configs',
                'ordering': ['tower_number'],
                'unique_together': {('project', 'tower_number')},
            },
        ),
    ]
