# Generated by Django 4.2.7 on 2025-12-14 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_towerfloorconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitconfiguration',
            name='is_commercial',
            field=models.BooleanField(default=False, help_text='Is this unit on a commercial floor?'),
        ),
    ]
