# Generated by Django 4.2.7 on 2025-12-18 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_add_is_commercial_to_unit_configuration'),
    ]

    operations = [
        migrations.CreateModel(
            name='HighrisePricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False, help_text='Enable highrise pricing for this project')),
                ('floor_threshold', models.IntegerField(default=10, help_text='Floor number where pricing starts to change (e.g., 10 = floors 1-10 have base price, 11+ have increased price)')),
                ('base_price_per_sqft', models.DecimalField(blank=True, decimal_places=2, help_text='Base price per sqft for floors up to threshold', max_digits=10, null=True)),
                ('pricing_type', models.CharField(choices=[('fixed', 'Fixed Price Addition'), ('per_sqft', 'Per Sqft Addition')], default='per_sqft', help_text='How price increases for floors above threshold', max_length=20)),
                ('fixed_price_increment', models.DecimalField(decimal_places=2, default=0.0, help_text="Fixed amount to add per floor above threshold (if pricing_type = 'fixed')", max_digits=10)),
                ('per_sqft_increment', models.DecimalField(decimal_places=2, default=0.0, help_text='Amount to add per sqft per floor above threshold (e.g., 20 = ₹20/sqft per floor)', max_digits=10)),
                ('development_charges_type', models.CharField(choices=[('fixed', 'Fixed Amount'), ('per_sqft', 'Per Sqft')], default='fixed', help_text='How development charges are calculated', max_length=20)),
                ('development_charges_fixed', models.DecimalField(decimal_places=2, default=0.0, help_text="Fixed development charges amount (if development_charges_type = 'fixed')", max_digits=10)),
                ('development_charges_per_sqft', models.DecimalField(decimal_places=2, default=0.0, help_text="Development charges per sqft (if development_charges_type = 'per_sqft')", max_digits=10)),
                ('parking_price', models.DecimalField(decimal_places=2, default=0.0, help_text='Parking price', max_digits=10)),
                ('parking_negotiable', models.BooleanField(default=False, help_text='Is parking price negotiable?')),
                ('include_parking_in_calculation', models.BooleanField(default=True, help_text='Include parking in total calculation')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='highrise_pricing', to='projects.project')),
            ],
            options={
                'db_table': 'highrise_pricing',
            },
        ),
    ]
