# Generated by Django 4.2.7 on 2026-01-01 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_add_highrise_pricing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highrisepricing',
            name='fixed_price_increment',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text="Fixed total amount to add per range (if pricing_type = 'fixed_total') OR fixed per sqft amount (if pricing_type = 'fixed_sqft')", max_digits=10),
        ),
        migrations.AlterField(
            model_name='highrisepricing',
            name='pricing_type',
            field=models.CharField(choices=[('fixed_total', 'Fixed Total Price Addition'), ('fixed_sqft', 'Fixed Per Sqft Addition'), ('per_sqft', 'Per Sqft Addition')], default='per_sqft', help_text='How price increases for floors above threshold', max_length=20),
        ),
    ]
