# Generated by Django 4.2.7 on 2026-01-05 07:07

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_alter_highrisepricing_fixed_price_increment_and_more'),
        ('bookings', '0004_commission'),
    ]

    operations = [
        # Add unit status fields
        migrations.AddField(
            model_name='unitconfiguration',
            name='status',
            field=models.CharField(
                choices=[
                    ('available', 'Available'),
                    ('reserved', 'Reserved'),
                    ('booked', 'Booked'),
                    ('blocked', 'Blocked'),
                    ('maintenance', 'Under Maintenance'),
                    ('sold', 'Sold'),
                ],
                default='available',
                help_text='Current status of this unit',
                max_length=20
            ),
        ),
        migrations.AddField(
            model_name='unitconfiguration',
            name='blocked_by',
            field=models.ForeignKey(
                blank=True,
                help_text='User who blocked this unit',
                null=True,
                on_delete=models.SET_NULL,
                related_name='blocked_units',
                to='accounts.user'
            ),
        ),
        migrations.AddField(
            model_name='unitconfiguration',
            name='blocked_at',
            field=models.DateTimeField(
                blank=True,
                help_text='When this unit was blocked',
                null=True
            ),
        ),
        migrations.AddField(
            model_name='unitconfiguration',
            name='blocked_until',
            field=models.DateTimeField(
                blank=True,
                help_text='Block expiry time',
                null=True
            ),
        ),
        migrations.AddField(
            model_name='unitconfiguration',
            name='booking',
            field=models.ForeignKey(
                blank=True,
                help_text='Booking associated with this unit',
                null=True,
                on_delete=models.SET_NULL,
                related_name='unit_configuration',
                to='bookings.booking'
            ),
        ),
        migrations.AddField(
            model_name='unitconfiguration',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes about this unit'),
        ),
        migrations.AddField(
            model_name='unitconfiguration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
        ),
        migrations.AddField(
            model_name='unitconfiguration',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        # Set default values for existing records
        migrations.RunSQL(
            "UPDATE unit_configurations SET status = 'available' WHERE status IS NULL",
            reverse_sql="UPDATE unit_configurations SET status = NULL WHERE status = 'available'"
        ),
        migrations.RunSQL(
            "UPDATE unit_configurations SET created_at = datetime('now') WHERE created_at IS NULL",
            reverse_sql="UPDATE unit_configurations SET created_at = NULL WHERE created_at IS NOT NULL"
        ),
        migrations.RunSQL(
            "UPDATE unit_configurations SET updated_at = datetime('now') WHERE updated_at IS NULL",
            reverse_sql="UPDATE unit_configurations SET updated_at = NULL WHERE updated_at IS NOT NULL"
        ),
    ]
