# Generated by Django 4.2.7 on 2026-01-12 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_auto_20260105_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitconfiguration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
