"""
Django settings for bridgio project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure--1r#3zpxed2&&*=+nnghvuyp++s=nr%y9p0kk9k487ae5c0z)1')

# SECURITY WARNING: don't run with debug turned on in production!
# Temporarily enable DEBUG if DEBUG_ENV is set to 'True' for troubleshooting
DEBUG_ENV = os.environ.get('DEBUG', 'False')
DEBUG = DEBUG_ENV == 'True' or DEBUG_ENV == 'true'

# ALLOWED_HOSTS - handle both comma-separated and default values
ALLOWED_HOSTS_ENV = os.environ.get('ALLOWED_HOSTS', '')
if ALLOWED_HOSTS_ENV:
    ALLOWED_HOSTS = [host.strip() for host in ALLOWED_HOSTS_ENV.split(',') if host.strip()]
else:
    # Default to common Render domains if not set
    ALLOWED_HOSTS = ['localhost', '127.0.0.1', '.onrender.com']

# Google Maps API Key for Attendance Features
GOOGLE_MAPS_API_KEY = os.environ.get('GOOGLE_MAPS_API_KEY', 'AIzaSyCwcFvh1vVe979dldumRkBnV01VU3msn30')

# OTP Secret for HMAC hashing (use a different secret than SECRET_KEY for additional security)
OTP_SECRET = os.environ.get('OTP_SECRET', SECRET_KEY)  # Defaults to SECRET_KEY if not set

# SMS Provider Configuration
SMS_PROVIDER = os.environ.get('SMS_PROVIDER', 'whatsapp').lower()  # Options: 'twilio', 'msg91', 'whatsapp'
TWILIO_ACCOUNT_SID = os.environ.get('TWILIO_ACCOUNT_SID', '')
TWILIO_AUTH_TOKEN = os.environ.get('TWILIO_AUTH_TOKEN', '')
TWILIO_PHONE_NUMBER = os.environ.get('TWILIO_PHONE_NUMBER', '')
MSG91_API_KEY = os.environ.get('MSG91_API_KEY', '')
MSG91_SENDER_ID = os.environ.get('MSG91_SENDER_ID', 'BRIDIO')
MSG91_TEMPLATE_ID = os.environ.get('MSG91_TEMPLATE_ID', '')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_htmx',
    'accounts',
    'projects',
    'leads',
    'bookings',
    'attendance',
    'channel_partners',
    'reports',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Add WhiteNoise for static files
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_htmx.middleware.HtmxMiddleware',
]

ROOT_URLCONF = 'bridgio.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'bridgio.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# Support multiple deployment platforms:
# 1. PostgreSQL (Railway, Heroku, DigitalOcean) - via DATABASE_URL
# 2. SQLite on persistent disk (Render, Fly.io) - via PERSISTENT_DISK_PATH or /data
# 3. SQLite local (development)

# Check for PostgreSQL first (Railway, Heroku, etc.)
DATABASE_URL = os.environ.get('DATABASE_URL')
if DATABASE_URL:
    try:
        import dj_database_url
        DATABASES = {
            'default': dj_database_url.parse(DATABASE_URL)
        }
    except ImportError:
        # Fallback to SQLite if dj_database_url not installed
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': BASE_DIR / 'db.sqlite3',
            }
        }
else:
    # Use SQLite with persistent disk support
    # Check for persistent disk paths (Render: /var/data, Fly.io: /data)
    PERSISTENT_DISK_PATH = os.environ.get('PERSISTENT_DISK_PATH', None)
    
    # Try common persistent disk paths
    persistent_paths = []
    if PERSISTENT_DISK_PATH:
        persistent_paths.append(PERSISTENT_DISK_PATH)
    persistent_paths.extend(['/var/data', '/data'])  # Render and Fly.io defaults
    
    db_path = None
    for path in persistent_paths:
        if os.path.exists(path):
            db_path = os.path.join(path, 'db.sqlite3')
            db_dir = path
            break
    
    # Fallback to project directory (for local development)
    if not db_path:
        db_path = BASE_DIR / 'db.sqlite3'
        db_dir = db_path.parent
        if not db_dir.exists():
            db_dir.mkdir(parents=True, exist_ok=True)
        db_path = str(db_path)
    else:
        # Ensure persistent disk directory exists
        if not os.path.exists(db_dir):
            os.makedirs(db_dir, exist_ok=True)
    
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': db_path,
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# WhiteNoise for static files serving in production
if not DEBUG:
    # Use CompressedStaticFilesStorage instead of CompressedManifestStaticFilesStorage
    # to avoid issues if staticfiles.json doesn't exist
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'

# Logging configuration for production
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'accounts': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
    },
}

# Custom User Model
AUTH_USER_MODEL = 'accounts.User'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Login URLs
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/accounts/login/'
