# Generated by Django 4.2.7 on 2025-11-28 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_commercial_floors_and_more'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_projects',
            field=models.ManyToManyField(blank=True, help_text='Projects assigned to this telecaller (for telecallers only)', related_name='assigned_telecallers', to='projects.project'),
        ),
    ]
