# Generated by Django 4.2.7 on 2025-11-28 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firm_name', models.CharField(max_length=200)),
                ('cp_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('rera_id', models.CharField(blank=True, max_length=50)),
                ('cp_type', models.CharField(choices=[('broker', 'Broker'), ('agency', 'Agency'), ('individual', 'Individual')], default='broker', max_length=20)),
                ('working_area', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_projects', models.ManyToManyField(blank=True, related_name='channel_partners', to='projects.project')),
            ],
            options={
                'db_table': 'channel_partners',
                'ordering': ['-created_at'],
            },
        ),
    ]
