# Generated by Django 4.2.7 on 2025-11-28 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel_partners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelpartner',
            name='cp_unique_id',
            field=models.CharField(blank=True, db_index=True, max_length=5, null=True, unique=True),
        ),
    ]
