# Generated by Django 4.2.7 on 2025-11-30 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel_partners', '0002_channelpartner_cp_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelpartner',
            name='locality',
            field=models.CharField(blank=True, help_text='Locality/Area', max_length=200),
        ),
        migrations.AddField(
            model_name='channelpartner',
            name='owner_name',
            field=models.CharField(blank=True, help_text='Owner/Proprietor name', max_length=200),
        ),
        migrations.AddField(
            model_name='channelpartner',
            name='owner_number',
            field=models.CharField(blank=True, help_text='Owner contact number', max_length=15),
        ),
        migrations.AddField(
            model_name='channelpartner',
            name='phone2',
            field=models.CharField(blank=True, help_text='Secondary phone number', max_length=15),
        ),
        migrations.AddField(
            model_name='channelpartner',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], db_index=True, default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='channelpartner',
            name='team_size',
            field=models.IntegerField(blank=True, help_text='Number of team members', null=True),
        ),
    ]
