# Generated by Django 4.2.7 on 2026-01-06 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('channel_partners', '0003_channelpartner_locality_channelpartner_owner_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelpartner',
            name='sourcing_manager',
            field=models.ForeignKey(blank=True, help_text='Sourcing Manager assigned to this Channel Partner (1:1 relationship)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_channel_partners', to=settings.AUTH_USER_MODEL),
        ),
    ]
