# Generated by Django 4.2.7 on 2025-12-07 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='credited_to_closing_manager',
            field=models.ForeignKey(blank=True, help_text='Closing manager who gets credit for this booking', limit_choices_to={'role': 'closing_manager'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credited_bookings_closing', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='credited_to_sourcing_manager',
            field=models.ForeignKey(blank=True, help_text='Sourcing manager who gets credit for this booking (if CP lead)', limit_choices_to={'role': 'sourcing_manager'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credited_bookings_sourcing', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='credited_to_telecaller',
            field=models.ForeignKey(blank=True, help_text='Telecaller who gets credit for this booking (if telecaller-generated lead)', limit_choices_to={'role': 'telecaller'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credited_bookings_telecaller', to=settings.AUTH_USER_MODEL),
        ),
    ]
