# Generated by Django 4.2.7 on 2025-12-18 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0023_change_booking_to_foreignkey'),
        ('bookings', '0002_booking_credited_to_closing_manager_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='leads.lead'),
        ),
    ]
