# Generated by Django 4.2.7 on 2026-01-05 02:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('channel_partners', '0003_channelpartner_locality_channelpartner_owner_name_and_more'),
        ('bookings', '0003_change_booking_to_foreignkey'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_type', models.CharField(choices=[('cp', 'Channel Partner'), ('employee', 'Employee'), ('referral', 'Referral')], max_length=20)),
                ('commission_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('base_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('calculation_basis', models.CharField(choices=[('booking_amount', 'Booking Amount'), ('payment_received', 'Payment Received'), ('token_amount', 'Token Amount')], default='booking_amount', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Commission calculation notes or payment details')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commissions_approved', to=settings.AUTH_USER_MODEL)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='bookings.booking')),
                ('channel_partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commissions', to='channel_partners.channelpartner')),
                ('employee', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['closing_manager', 'sourcing_manager', 'telecaller']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commissions_received', to=settings.AUTH_USER_MODEL)),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commissions_paid', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'commissions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['booking', 'commission_type'], name='commissions_booking_7e96e0_idx'), models.Index(fields=['status', 'commission_type'], name='commissions_status_9d6f9b_idx'), models.Index(fields=['channel_partner', 'status'], name='commissions_channel_a7d81c_idx'), models.Index(fields=['employee', 'status'], name='commissions_employe_cbaafc_idx')],
            },
        ),
    ]
